### ISSUE TITLE
Case of big session - Error :  JavaScript heap out of memory

### ISSUE THREAD

**Issue by ghost** [opentech-ux/lom-session-compiler#1]
When a big session, with lots of chunks, is compiled, the systems hangs on with the following error:
```
Compiling sessions/58e3c30d-d977-4464-96ef-dd9d9aad9806 in build/sessions/58e3c30d-d977-4464-96ef-dd9d9aad9806

<--- Last few GCs --->

[69955:0x7fdfd2200000]    28835 ms: Mark-sweep 4029.4 (4129.1) -> 4028.7 (4129.1) MB, 2731.5 / 0.0 ms  (average mu = 0.648, current mu = 0.278) allocation failure scavenge might not succeed
[69955:0x7fdfd2200000]    35026 ms: Mark-sweep 4044.4 (4129.1) -> 4043.7 (4161.1) MB, 5964.8 / 0.0 ms  (average mu = 0.303, current mu = 0.036) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x102dea5f5 node::Abort() (.cold.1) [/Users/nizarayed/.nvm/versions/node/v16.18.1/bin/node]
 2: 0x101adff49 node::Abort() [/Users/nizarayed/.nvm/versions/node/v16.18.1/bin/node]
...
...
...
```

As the regular memory space size is 1.7 Gb for NodeJS, one solution is to put define the following: `NODE_OPTIONS='--max-old-space-size=4096'`.
It didn't work.

The memory was increased to 8192: The error is now: 
```
/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/SessionCompiler.js:254
            const sessionJSON = JSON.stringify(this.session);
                                     ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at SessionCompiler.<anonymous> (/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/SessionCompiler.js:254:38)
    at Generator.next (<anonymous>)
    at /Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/SessionCompiler.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/SessionCompiler.js:27:12)
    at SessionCompiler.compile (/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/SessionCompiler.js:157:16)
    at CompilationContextImpl.<anonymous> (/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/CompilationContextImpl.js:83:74)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nizarayed/Documents/002-git/uxkey/local-op-st-server/node_modules/@opentech-ux/lom-session-compiler/dist/lib/CompilationContextImpl.js:28:58)
```

**Comment by ghost** [comment]
For additional information, here are the [session files](https://drive.google.com/file/d/1T7SU7n2X-AlKn7OtKZ1vAz7t83eDXDVg/view?usp=share_link).
The link is protected and limited only the repository maintainers.
Some stats about the files :
* Number of chunks: 733 chunks.
* Total size of session: 334 MB.
